Switch telephony-ext to a static library
*** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/codeaurora/internal/IExtTelephony$Stub;
	at com.android.server.telecom.TelephonyUtil.isLocalEmergencyNumber(TelephonyUtil.java:77)
	at com.android.server.telecom.TelephonyUtil.shouldProcessAsEmergency(TelephonyUtil.java:72)
	at com.android.server.telecom.components.UserCallIntentProcessor.processOutgoingCallIntent(UserCallIntentProcessor.java:109)
	at com.android.server.telecom.components.UserCallIntentProcessor.processIntent(UserCallIntentProcessor.java:88)
	at com.android.server.telecom.TelecomServiceImpl$1.placeCall(TelecomServiceImpl.java:1083)
	at com.android.internal.telecom.ITelecomService$Stub.onTransact(ITelecomService.java:549)
	at android.os.Binder.execTransact(Binder.java:565)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.codeaurora.internal.IExtTelephony$Stub" on path: DexPathList[[zip file "/system/priv-app/Telecom/Telecom.apk"],nativeLibraryDirectories=[/system/priv-app/Telecom/lib/arm64,
/system/priv-app/Telecom/Telecom.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 7 more
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/codeaurora/internal/IExtTelephony$Stub;
	at com.android.server.telecom.TelephonyUtil.isLocalEmergencyNumber(TelephonyUtil.java:77)
	at com.android.server.telecom.TelephonyUtil.shouldProcessAsEmergency(TelephonyUtil.java:72)
	at com.android.server.telecom.components.UserCallIntentProcessor.processOutgoingCallIntent(UserCallIntentProcessor.java:109)
	at com.android.server.telecom.components.UserCallIntentProcessor.processIntent(UserCallIntentProcessor.java:88)
	at com.android.server.telecom.TelecomServiceImpl$1.placeCall(TelecomServiceImpl.java:1083)
	at com.android.internal.telecom.ITelecomService$Stub.onTransact(ITelecomService.java:549)
	at android.os.Binder.execTransact(Binder.java:565)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "org.codeaurora.internal.IExtTelephony$Stub" on path: DexPathList[[zip file "/system/priv-app/Telecom/Telecom.apk"],nativeLibraryDirectories=[/system/priv-app/Telecom/lib/arm64,
/system/priv-app/Telecom/Telecom.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 	... 7 more

Change-Id: Icc1ea74f348f47a2886a0c88eabc2a4538cad485
Signed-off-by: Alexander Martinz <eviscerationls@gmail.com>