Telecom: fix test releated compile error, which is due to missing CMSDK dependencies.
Add org.cyanogenmod.platform.internal and uicommon to LOCAL_STATIC_JAVA_LIBRARIES to fix the
following compile error:

ERROR: /packages/services/Telecomm/src/com/android/server/telecom/Ringer.java:30: The import cyanogenmod cannot be resolved
ERROR: /packages/services/Telecomm/src/com/android/server/telecom/Ringer.java:131: CMSettings cannot be resolved
...
ERROR: /packages/services/Telecomm/src/com/android/server/telecom/ui/MissedCallNotifierImpl.java:84: The import cyanogenmod cannot be resolved
ERROR: /packages/services/Telecomm/src/com/android/server/telecom/ui/MissedCallNotifierImpl.java:578: CMSettings cannot be resolved

Change-Id: Ic5f190300fce44fec6be871ccfce53d57fcf86f5